### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kovalenkos** [trebuchetty/Handsontable-select2-editor#3]
hello!

Uncaught TypeError: Cannot read property 'appendChild' of undefined

41. this.instance.rootElement[0].appendChild(this.TEXTAREA_PARENT);

error

**Comment by trebuchetty** [comment]
What version on handsontable and Select2 are you using with this?

**Comment by kovalenkos** [comment]
Handsontable 0.12.2

**Comment by motin** [comment]
Same here. 
Handsontable 0.12.4
Select2 3.5.2

**Comment by timberswrx** [comment]
Any fix for this? I have the same issue.

**Comment by motin** [comment]
Check the referenced commit above for a fix

**Comment by timberswrx** [comment]
OK, thanks, made that change. Now I get "undefined is not a function".

**Comment by motin** [comment]
Yeah, for full support for Handsontable 0.12, see this PR: https://github.com/trebuchetty/Handsontable-select2-editor/pull/4

**Comment by timberswrx** [comment]
Is anyone successfully using this with Handsontable 0.12? I got the updated file from #4 above, but I'm still getting the same error at line 145. "Uncaught TypeError: undefined is not a function". 

Thanks

**Comment by motin** [comment]
We use we it. 

Using the following in bower:

    "Handsontable-select2-editor": "https://github.com/motin/Handsontable-select2-editor.git#4ec18ace630816f00e7275ea04a2019f23ccf432",
    "select2": "~3.5.2"

Including select2.js and select2.css from select2 first and then select2-editor.js from this repo.

**Comment by timberswrx** [comment]
Thanks for your help. That has fixed all my issues.

**Comment by trebuchetty** [comment]
I haven't had the chance to test these changes as I'm not able to update my project's version of Handsontable (no time or buy in from stakeholders), so I've been holding back on integrating the merges to fix these issues. I will get to this soon though.

**Comment by mpusarla** [comment]
I picked up the patch and tried but it is not working. When selecting an entry, the id is getting displayed and dropdown is not aligned properly. Can you let me know if i am missing anything?
Here is the sample: http://jsfiddle.net/mpusarla/uh9jxo8v/5/

**Comment by timberswrx** [comment]
I'm getting exactly the same result. I added a new issue about it, but have received no help with it. I ended up not using this in my project.

**Comment by mpusarla** [comment]
We are able to get the select2-editor working with Handsontable 0.12.4. To fix the alignment issue, had to comment the following:
this.$textarea.offset($(this.TD).offset());
Added custom renderer for displaying the text instead of the id. Here is the jsfiddle: http://jsfiddle.net/mpusarla/4mpyhbjw/35/

**Comment by trebuchetty** [comment]
I've merged in the original change to fix this issue and merged in the changes by @motin that seems to have fixed the rest of the issues. I also created a jsFiddle (link on readme) that shows how to use this editor. Showing something in the grid (ie. after selection) other than the id selected is out of the scope of this editor (requires a custom renderer). Closing.
